//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoT_Lib.DBClass
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class IoT_ClassEntities : DbContext
    {
        public IoT_ClassEntities()
            : base("name=IoT_ClassEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Student> Student { get; set; }
        public DbSet<Task> Task { get; set; }
        public DbSet<Task_Log> Task_Log { get; set; }
        public DbSet<RFID> RFID { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    
        public virtual int usp_getGroup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_getGroup");
        }
    }
}
