//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoT_Lib.DBClass
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Log
    {
        public System.Guid ID { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string UpdateStudent { get; set; }
        public string UpdateIP { get; set; }
        public string Data { get; set; }
        public int IsVerification { get; set; }
        public System.Guid TaskID { get; set; }

        [JsonIgnore]
        public virtual Task Task { get; set; }
    }
}
